// DocView.jsx
"use client";
import React from "react";
import TextFormat from "../format/TextFormat";

export function DocView({ pages, fontSize = 16, deviceDimensions = { width: 720, height: 520 } }) {
  const pageWidth = Math.min(deviceDimensions.width, 860);   // nice readable width
  const pageMinHeight = Math.max(deviceDimensions.height, 980); // tall sheet feel

  return (
    <div style={{ padding: "12px 0 24px" }}>
      <div
        style={{
          display: "flex",
          justifyContent: "center",
          gap: 16,
          flexWrap: "wrap",
          alignItems: "flex-start",
        }}
      >
        {pages.map((page, i) => (
          <div
            key={i}
            style={{
              width: pageWidth,
              minHeight: pageMinHeight,
              background: "#fff",
              borderRadius: 12,
              border: "1px solid #e5e7eb",
              boxShadow:
                "0 4px 10px rgba(0,0,0,.06), 0 20px 40px rgba(0,0,0,.04)",
              overflow: "hidden",
              display: "flex",
              flexDirection: "column",
            }}
          >
            {/* Header */}
            <div
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                padding: "10px 16px",
                borderBottom: "1px solid #eef2f7",
                background:
                  "linear-gradient(180deg, rgba(248,250,252,0.9) 0%, rgba(255,255,255,0.9) 100%)",
              }}
            >
              <span
                style={{
                  fontSize: 12,
                  fontWeight: 600,
                  color: "#64748b",
                  letterSpacing: ".02em",
                }}
              >
                Document View
              </span>
              <span
                style={{
                  fontSize: 12,
                  color: "#94a3b8",
                }}
              >
                Page {i + 1}
              </span>
            </div>

            {/* Page body */}
            <div
              style={{
                flex: 1,
                padding: "22px 28px",
                fontSize,
                lineHeight: 1.7,
                color: "#1f2937",
                background:
                  "repeating-linear-gradient(0deg, transparent, transparent 31px, rgba(0,0,0,0.02) 31px, rgba(0,0,0,0.02) 32px)", // subtle rhythm
              }}
            >
              <TextFormat data={page} />
            </div>

            {/* Footer */}
            <div
              style={{
                padding: "8px 16px",
                borderTop: "1px solid #eef2f7",
                background: "#fbfdff",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
              }}
            >
              <span style={{ fontSize: 11, color: "#94a3b8" }}>
                Generated by TBM+
              </span>
              <span
                style={{
                  fontSize: 11,
                  color: "#64748b",
                  fontVariantNumeric: "tabular-nums",
                }}
              >
                {i + 1} / {pages.length}
              </span>
            </div>
          </div>
        ))}
      </div>

      {/* Print-friendly tweaks */}
      <style>{`
        @media (max-width: 768px) {
          /* make sheets fill nicely on mobile */
          div[data-docview] { padding: 8px 0 16px; }
        }

        @media print {
          /* simple print style: one page per sheet */
          body { background: #fff !important; }
          * { box-shadow: none !important; }
          .doc-sheet {
            page-break-after: always;
            border: none !important;
            border-radius: 0 !important;
            width: auto !important;
            min-height: auto !important;
            box-shadow: none !important;
          }
        }
      `}</style>
    </div>
  );
}
